# Generated by Django 5.1.2 on 2024-10-10 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='M', max_length=12, null=True)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('KY', 'Kentucky'), ('OH', 'Ohio'), ('AK', 'Alaska'), ('LA', 'Louisiana'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('ME', 'Maine'), ('OR', 'Oregon'), ('AR', 'Arkansas'), ('MD', 'Maryland'), ('PA', 'Pennsylvania'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire'), ('CA', 'California'), ('MI', 'Michigan'), ('RI', 'Rhode Island'), ('CO', 'Colorado'), ('MN', 'Minnesota'), ('SC', 'South Carolina'), ('CT', 'Connecticut'), ('MS', 'Mississippi'), ('SD', 'South Dakota'), ('DE', 'Delaware'), ('MO', 'Missouri'), ('TN', 'Tennessee'), ('MT', 'Montana'), ('TX', 'Texas'), ('FL', 'Florida'), ('NE', 'Nebraska'), ('GA', 'Georgia'), ('NV', 'Nevada'), ('UT', 'Utah'), ('VT', 'Vermont'), ('HI', 'Hawaii'), ('NJ', 'New Jersey'), ('VA', 'Virginia'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('IL', 'Illinois'), ('NY', 'New York'), ('WA', 'Washington'), ('IN', 'Indiana'), ('NC', 'North Carolina'), ('WV', 'West Virginia'), ('IA', 'Iowa'), ('ND', 'North Dakota'), ('WI', 'Wisconsin'), ('KS', 'Kansas'), ('WY', 'Wyoming')], default='AL', max_length=2)),
                ('zipcode', models.CharField(max_length=12)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('contact', models.ManyToManyField(to='custom_users.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_alert', models.CharField(db_comment='Time before due date when email notification is sent', default='30d', max_length=24)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_users.contact')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('A', 'Alternative'), ('O', 'Other')], default='P', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.ManyToManyField(to='custom_users.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('H', 'Home'), ('W', 'Work'), ('O', 'Other')], default='M', max_length=1)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format $xxx xxx-xxxx.', regex='^[0-9]{3} [0-9]{3}-[0-9]{4}$')])),
                ('contact', models.ManyToManyField(to='custom_users.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
