# Generated by Django 5.1.2 on 2024-10-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contact', to='custom_users.contact'),
        ),
    ]
