# Generated by Django 5.1.1 on 2024-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_rename_value_phonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='type',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='cell_type',
            field=models.CharField(choices=[('M', 'Mobile'), ('H', 'Home'), ('W', 'Work'), ('O', 'Other')], default='M', max_length=8),
        ),
    ]
