# Generated by Django 5.1.2 on 2024-10-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_remove_address_contact_remove_email_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='category',
            field=models.CharField(blank=True, choices=[('J', 'Job Site'), ('M', 'Home'), ('C', 'Company'), ('O', 'Other')], default='M', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_contact', to='custom_users.contact'),
        ),
        migrations.CreateModel(
            name='VendorCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_vendor_customer', to='custom_users.contact')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_vendor', to='custom_users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='vendor_to_customer',
            field=models.ManyToManyField(through='custom_users.VendorCustomer', to='custom_users.contact'),
        ),
    ]
