# Generated by Django 5.1.2 on 2024-10-13 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_uuid', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=254)),
                ('issued_at', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_recipient', to='custom_users.contact')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_issuer', to='custom_users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=254)),
                ('completion_date', models.DateField()),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_seller', to='custom_users.contact')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0, validators=[django.core.validators.RegexValidator(message='Format must be in 00.00', regex='[0-9]+\\.[0-9]{2}')])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=254)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_job_site', to='custom_users.contact')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorder')),
            ],
        ),
    ]
