# Generated by Django 5.1.1 on 2024-10-02 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0002_rename_value_phonenumber_phone_number_and_more'),
        ('logger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=254)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_item_id', models.IntegerField(unique=True)),
                ('cost', models.FloatField()),
                ('name', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.CharField(max_length=254)),
                ('issued_at', models.DateField()),
                ('deadline', models.DateField()),
                ('custom_alert_time', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.vendor'),
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('title', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=64)),
                ('descript', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('work_order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoice.workorder')),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logger.filemeta')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.contact')),
            ],
        ),
    ]
