# Generated by Django 5.1.2 on 2024-10-19 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.address')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=64)),
                ('order_descript', models.CharField(max_length=254)),
                ('completion_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('N', 'Not Assigned'), ('A', 'Assigned'), ('U', 'Under Review')], default='N', max_length=1)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.jobsite')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='custom_users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0, validators=[django.core.validators.RegexValidator(message='Format must be in 00.00', regex='[0-9]+\\.[0-9]{2}')])),
                ('memo', models.CharField(max_length=64, null=True)),
                ('descript', models.CharField(max_length=254, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(max_length=64)),
                ('invoice_descript', models.CharField(max_length=254)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='custom_users.customer')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer', to='custom_users.usercontactinfo')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.workorder')),
            ],
        ),
    ]
