# Generated by Django 5.1.2 on 2024-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='work_order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_orders',
            field=models.ManyToManyField(to='invoice.workorder'),
        ),
    ]
