# Generated by Django 5.1.2 on 2024-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateField(),
        ),
    ]
