# Generated by Django 5.1.1 on 2024-10-04 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_rename_value_phonenumber_phone_number_and_more'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='vendor_id',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='contact_id',
            new_name='seller_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='custom_alert_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='work_item_id',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='work_order_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_users.contact'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='work_order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoice.workorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Vendor',
        )
        
    ]
