# Generated by Django 5.1.2 on 2024-10-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_descript_invoice_invoice_descript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
