# Generated by Django 5.1.2 on 2024-10-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_alter_vendor_uuid_alter_vendor_vendor_contact'),
        ('invoice', '0002_alter_invoice_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='custom_users.customer'),
        ),
    ]
