# Generated by Django 5.1.2 on 2024-10-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_uuid_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceattachment',
            name='upload_file',
            field=models.FileField(default=None, upload_to='invoice_attachments/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
